# Generated by Django 3.0.3 on 2020-02-10 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rice_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_number', models.IntegerField()),
                ('last_delivery_date', models.DateTimeField(auto_now=True)),
                ('today_number', models.IntegerField()),
                ('today_data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('is_saling', models.BooleanField(default=True)),
                ('owned_number', models.IntegerField()),
                ('last_supple_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('register_date', models.DateField()),
                ('last_work_date', models.DateField()),
                ('is_office', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_number', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rice_model.Product')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rice_model.Worker')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='worker',
            field=models.ManyToManyField(through='rice_model.Delivery', to='rice_model.Worker'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rice_model.Product'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rice_model.Worker'),
        ),
    ]
