# Generated by Django 3.0.3 on 2020-02-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rice_model', '0002_auto_20200210_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_saling',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_office',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='ON_SALE', max_length=10),
        ),
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.CharField(default='ON', max_length=10),
        ),
    ]
