# Generated by Django 3.0.3 on 2020-02-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rice_model', '0003_auto_20200212_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='label',
        ),
    ]
